//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presenter.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For queries, suggestions or bug fixes please contact us at:.
        /// </summary>
        public static string AboutDesc {
            get {
                return ResourceManager.GetString("AboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string AboutEmailTitle {
            get {
                return ResourceManager.GetString("AboutEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum:.
        /// </summary>
        public static string AboutForumTitle {
            get {
                return ResourceManager.GetString("AboutForumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiovisual Presenter.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutVersionTitle {
            get {
                return ResourceManager.GetString("AboutVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string AboutWebsiteTitle {
            get {
                return ResourceManager.GetString("AboutWebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred and been logged.
        /// </summary>
        public static string AppError {
            get {
                return ResourceManager.GetString("AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred processing an image file..
        /// </summary>
        public static string AppImageError {
            get {
                return ResourceManager.GetString("AppImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program requires Microsoft Office XP with PowerPoint or greater..
        /// </summary>
        public static string AppRequiresOffice {
            get {
                return ResourceManager.GetString("AppRequiresOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program requires Microsoft SQL Server Compact 3.5 Service Pack 1..
        /// </summary>
        public static string AppRequiresSql {
            get {
                return ResourceManager.GetString("AppRequiresSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires Windows Media Player 10 or higher to play video or audio files..
        /// </summary>
        public static string AppRequiresWMP {
            get {
                return ResourceManager.GetString("AppRequiresWMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BuildProgressCancel {
            get {
                return ResourceManager.GetString("BuildProgressCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal Notation.
        /// </summary>
        public static string ColorPickerHex {
            get {
                return ResourceManager.GetString("ColorPickerHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Color.
        /// </summary>
        public static string ColorPickerSelectedColor {
            get {
                return ResourceManager.GetString("ColorPickerSelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Color.
        /// </summary>
        public static string ColorPickerWindowTitle {
            get {
                return ResourceManager.GetString("ColorPickerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FullscreenVideoClose {
            get {
                return ResourceManager.GetString("FullscreenVideoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GenericCancel {
            get {
                return ResourceManager.GetString("GenericCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string GenericOk {
            get {
                return ResourceManager.GetString("GenericOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MainBtnAdd {
            get {
                return ResourceManager.GetString("MainBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MainBtnMoveDown {
            get {
                return ResourceManager.GetString("MainBtnMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MainBtnMoveUp {
            get {
                return ResourceManager.GetString("MainBtnMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MainBtnNext {
            get {
                return ResourceManager.GetString("MainBtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string MainBtnPrev {
            get {
                return ResourceManager.GetString("MainBtnPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainBtnRefresh {
            get {
                return ResourceManager.GetString("MainBtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MainBtnRemove {
            get {
                return ResourceManager.GetString("MainBtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MainBtnStart {
            get {
                return ResourceManager.GetString("MainBtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MainBtnStop {
            get {
                return ResourceManager.GetString("MainBtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string MainBtnTimer {
            get {
                return ResourceManager.GetString("MainBtnTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string MainBtnVideoPause {
            get {
                return ResourceManager.GetString("MainBtnVideoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string MainBtnVideoPlay {
            get {
                return ResourceManager.GetString("MainBtnVideoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek To.
        /// </summary>
        public static string MainBtnVideoSeek {
            get {
                return ResourceManager.GetString("MainBtnVideoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MainBtnVideoStop {
            get {
                return ResourceManager.GetString("MainBtnVideoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string MainBtnVideoVolume {
            get {
                return ResourceManager.GetString("MainBtnVideoVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MainContextAdd {
            get {
                return ResourceManager.GetString("MainContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected files?.
        /// </summary>
        public static string MainContextDeleteConfirm {
            get {
                return ResourceManager.GetString("MainContextDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string MainContextDeleteFile {
            get {
                return ResourceManager.GetString("MainContextDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string MainContextOpenFile {
            get {
                return ResourceManager.GetString("MainContextOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location.
        /// </summary>
        public static string MainContextOpenLocation {
            get {
                return ResourceManager.GetString("MainContextOpenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MainContextRemove {
            get {
                return ResourceManager.GetString("MainContextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press CTRL+R to end remote mode..
        /// </summary>
        public static string MainDescRemote {
            get {
                return ResourceManager.GetString("MainDescRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MainHeaderLibrary {
            get {
                return ResourceManager.GetString("MainHeaderLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Order.
        /// </summary>
        public static string MainHeaderOrder {
            get {
                return ResourceManager.GetString("MainHeaderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string MainLabelLiveJump {
            get {
                return ResourceManager.GetString("MainLabelLiveJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string MainLabelLiveNotes {
            get {
                return ResourceManager.GetString("MainLabelLiveNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        public static string MainLabelLiveSlide {
            get {
                return ResourceManager.GetString("MainLabelLiveSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string MainLabelLiveText {
            get {
                return ResourceManager.GetString("MainLabelLiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string MainLabelLocation {
            get {
                return ResourceManager.GetString("MainLabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MainLabelSearch {
            get {
                return ResourceManager.GetString("MainLabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MainMenuMessage {
            get {
                return ResourceManager.GetString("MainMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string MainMenuPlanner {
            get {
                return ResourceManager.GetString("MainMenuPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string MainMenuRemote {
            get {
                return ResourceManager.GetString("MainMenuRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string MainMenuReportList {
            get {
                return ResourceManager.GetString("MainMenuReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string MainMenuReportUsage {
            get {
                return ResourceManager.GetString("MainMenuReportUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File no longer exists..
        /// </summary>
        public static string MainMessageFileNotFound {
            get {
                return ResourceManager.GetString("MainMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder no longer exists..
        /// </summary>
        public static string MainMessageFolderNotFound {
            get {
                return ResourceManager.GetString("MainMessageFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add items to the presentation list first..
        /// </summary>
        public static string MainNoAddedItems {
            get {
                return ResourceManager.GetString("MainNoAddedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control mode can only be enabled once a presentation is started..
        /// </summary>
        public static string MainRemoteNotStart {
            get {
                return ResourceManager.GetString("MainRemoteNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string MainRootDirName {
            get {
                return ResourceManager.GetString("MainRootDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiovisual Presenter.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string OpenBtnDel {
            get {
                return ResourceManager.GetString("OpenBtnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string OpenBtnNew {
            get {
                return ResourceManager.GetString("OpenBtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenBtnOpen {
            get {
                return ResourceManager.GetString("OpenBtnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        public static string OpenDelConfirm {
            get {
                return ResourceManager.GetString("OpenDelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string OpenHeaderNew {
            get {
                return ResourceManager.GetString("OpenHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenHeaderOpen {
            get {
                return ResourceManager.GetString("OpenHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item has been selected..
        /// </summary>
        public static string OpenItemNotSelected {
            get {
                return ResourceManager.GetString("OpenItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date..
        /// </summary>
        public static string OpenMissingDate {
            get {
                return ResourceManager.GetString("OpenMissingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description..
        /// </summary>
        public static string OpenMissingDesc {
            get {
                return ResourceManager.GetString("OpenMissingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string OpenWindowTitle {
            get {
                return ResourceManager.GetString("OpenWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color Picker.
        /// </summary>
        public static string OptionsBackColor {
            get {
                return ResourceManager.GetString("OptionsBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string OptionsBtnBrowse {
            get {
                return ResourceManager.GetString("OptionsBtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank slide after PowerPoint files.
        /// </summary>
        public static string OptionsInsertBlankAfterPres {
            get {
                return ResourceManager.GetString("OptionsInsertBlankAfterPres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank slide after Video &amp; Sound files.
        /// </summary>
        public static string OptionsInsertBlankAfterVideo {
            get {
                return ResourceManager.GetString("OptionsInsertBlankAfterVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the root folder containing presentation files located in sub-folders..
        /// </summary>
        public static string OptionsLibraryBrowseDesc {
            get {
                return ResourceManager.GetString("OptionsLibraryBrowseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenter Library Path.
        /// </summary>
        public static string OptionsLibraryPath {
            get {
                return ResourceManager.GetString("OptionsLibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string OptionsMessengerFont {
            get {
                return ResourceManager.GetString("OptionsMessengerFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message settings.
        /// </summary>
        public static string OptionsMessengerLabel {
            get {
                return ResourceManager.GetString("OptionsMessengerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string OptionsMessengerPosition {
            get {
                return ResourceManager.GetString("OptionsMessengerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string OptionsMonitorPrimary {
            get {
                return ResourceManager.GetString("OptionsMonitorPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show presentations and videos on:.
        /// </summary>
        public static string OptionsMonitorSetting {
            get {
                return ResourceManager.GetString("OptionsMonitorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string OptionsMonitorTitle {
            get {
                return ResourceManager.GetString("OptionsMonitorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Settings.
        /// </summary>
        public static string OptionsPresentionSettings {
            get {
                return ResourceManager.GetString("OptionsPresentionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Preview Popup Delay (sec).
        /// </summary>
        public static string OptionsSlideDelay {
            get {
                return ResourceManager.GetString("OptionsSlideDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Preview Size.
        /// </summary>
        public static string OptionsSlideSize {
            get {
                return ResourceManager.GetString("OptionsSlideSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Customization.
        /// </summary>
        public static string OptionsWndCust {
            get {
                return ResourceManager.GetString("OptionsWndCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenter Library List.
        /// </summary>
        public static string ReportsListDocFilename {
            get {
                return ResourceManager.GetString("ReportsListDocFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library list as of.
        /// </summary>
        public static string ReportsListDocTitle {
            get {
                return ResourceManager.GetString("ReportsListDocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ReportsListOptionAll {
            get {
                return ResourceManager.GetString("ReportsListOptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what libraries you would like to list:.
        /// </summary>
        public static string ReportsListSelectionDesc {
            get {
                return ResourceManager.GetString("ReportsListSelectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library List Report.
        /// </summary>
        public static string ReportsListWindowTitle {
            get {
                return ResourceManager.GetString("ReportsListWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenter Usage Report.
        /// </summary>
        public static string ReportsUsageDocFilename {
            get {
                return ResourceManager.GetString("ReportsUsageDocFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenter usage report from {0} to {1}.
        /// </summary>
        public static string ReportsUsageDocTitle {
            get {
                return ResourceManager.GetString("ReportsUsageDocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ReportsUsageDownloadBtn {
            get {
                return ResourceManager.GetString("ReportsUsageDownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string ReportsUsageGenerateBtn {
            get {
                return ResourceManager.GetString("ReportsUsageGenerateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string ReportsUsageLabelFrom {
            get {
                return ResourceManager.GetString("ReportsUsageLabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ReportsUsageLabelTo {
            get {
                return ResourceManager.GetString("ReportsUsageLabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ReportsUsageOptionAll {
            get {
                return ResourceManager.GetString("ReportsUsageOptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ReportsUsageOptionOther {
            get {
                return ResourceManager.GetString("ReportsUsageOptionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what libraries you would like to include:.
        /// </summary>
        public static string ReportsUsageSelectionDesc {
            get {
                return ResourceManager.GetString("ReportsUsageSelectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Reports.
        /// </summary>
        public static string ReportsUsageWindowTitle {
            get {
                return ResourceManager.GetString("ReportsUsageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        public static string ShowMessageAddTimerDown {
            get {
                return ResourceManager.GetString("ShowMessageAddTimerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer starting at.
        /// </summary>
        public static string ShowMessageAddTimerMiddle1 {
            get {
                return ResourceManager.GetString("ShowMessageAddTimerMiddle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer finishing at.
        /// </summary>
        public static string ShowMessageAddTimerMiddle2 {
            get {
                return ResourceManager.GetString("ShowMessageAddTimerMiddle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a count.
        /// </summary>
        public static string ShowMessageAddTimerStart {
            get {
                return ResourceManager.GetString("ShowMessageAddTimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string ShowMessageAddTimerUp {
            get {
                return ResourceManager.GetString("ShowMessageAddTimerUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowMessageButton {
            get {
                return ResourceManager.GetString("ShowMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message:.
        /// </summary>
        public static string ShowMessageDesc {
            get {
                return ResourceManager.GetString("ShowMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box.
        /// </summary>
        public static string ShowMessageWindowTitle {
            get {
                return ResourceManager.GetString("ShowMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string SlideShowAudioLabel {
            get {
                return ResourceManager.GetString("SlideShowAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SlideShowImageLabel {
            get {
                return ResourceManager.GetString("SlideShowImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string SlideShowVideoLabel {
            get {
                return ResourceManager.GetString("SlideShowVideoLabel", resourceCulture);
            }
        }
    }
}
